# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "registry.gitlab.com/data-terrae/projects/captchacracker/captcha-cracker-model${tag}" --build-arg MODEL_PORT=88 ./model
    - docker build --pull -t "registry.gitlab.com/data-terrae/projects/captchacracker/captcha-cracker-webapp${tag}" --build-arg WEBAPP_PORT=8504 ./webapp
    - docker push "registry.gitlab.com/data-terrae/projects/captchacracker/captcha-cracker-model${tag}"
    - docker push "registry.gitlab.com/data-terrae/projects/captchacracker/captcha-cracker-webapp${tag}"

