version: "3.4"

services:

  webapp:
    # A simple web app' powered by Streamlit
    container_name: webapp_container
    restart: always
    build:
      context: ./webapp
      dockerfile: Dockerfile
      args:
        - WEBAPP_PORT
    env_file: .env
    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"
    environment:
      # These environment variables override the default values given in .env file
      - MODEL_HOSTNAME=model

  model:
    # The CaptchaCracker model served through a REST API
    container_name: model_container
    build:
      context: ./model
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${MODEL_PORT}:${MODEL_PORT}"