version: "3.4"

services:

  # A simple web app' powered by Streamlit
  webapp:
    container_name: webapp_container
    restart: always
    build: # Docker container is built from the /webapp folder
      context: ./webapp
      args:
        - WEBAPP_PORT
    env_file: .env # Default environment variables are loaded from .env file and passed to the webapp container
    environment:
      # These environment variables override the default values given in .env file
      - MODEL_HOSTNAME=model
    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"

  # The CaptchaCracker model served through a REST API
  model:
    container_name: model_container
    build: # Docker container is built from the /model folder
      context: ./model
    ports:
      - "${MODEL_PORT}:${MODEL_PORT}"