# Credentials for Gitlab Registry, where the Docker images of both model and webapp services are stored.

apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgImF1dGgiOiJZbXhoYm1kbE9tZHNjR0YwTFZWalJERXRRMHREUzBGMU4zaEtjMjVOTjNaWSIKICAgIAl9CiAgICB9Cn0K
